# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/lh/Documents/unreal_engine
GAMEPROJECTFILE =/home/lh/Documents/bs-engine/Biguasim.uproject

TARGETS = \
	Holodeck-Linux-DebugGame  \
	Holodeck-Linux-Shipping  \
	Holodeck \
	HolodeckEditor-Linux-DebugGame  \
	HolodeckEditor-Linux-Shipping  \
	HolodeckEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend BiguasimEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug BiguasimEditor-Linux-Debug


Holodeck-Linux-DebugGame:
	 $(BUILD) Holodeck Linux DebugGame  $(ARGS)

Holodeck-Linux-Shipping:
	 $(BUILD) Holodeck Linux Shipping  $(ARGS)

Holodeck:
	 $(BUILD) Holodeck Linux Development  $(ARGS)

HolodeckEditor-Linux-DebugGame:
	 $(BUILD) HolodeckEditor Linux DebugGame  $(ARGS)

HolodeckEditor-Linux-Shipping:
	 $(BUILD) HolodeckEditor Linux Shipping  $(ARGS)

HolodeckEditor:
	 $(BUILD) HolodeckEditor Linux Development  $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
